import type { BucketId, Shape, Verdict } from './types.js';

/** Stage 2: the same ten buckets with a verdict per construct. From the spec's mapping table. */
export interface MappingDef {
  id: string;
  bucket: BucketId;
  from: string;
  to: string;
  verdict: Verdict;
  shape?: Shape;
}

export const MAPPING_ROWS: readonly MappingDef[] = [
  {
    id: 'catalog.products',
    bucket: 'catalog',
    from: 'Products, price books',
    to: 'HubSpot product library, Quotivity price books',
    verdict: 'Clear path',
    shape: '1:1',
  },
  {
    id: 'catalog.multicurrency',
    bucket: 'catalog',
    from: 'Multi-currency price books',
    to: 'Price book entries carry a price per enabled portal currency',
    verdict: 'Clear path',
    shape: '1:1',
  },
  {
    id: 'catalog.dcrStatic',
    bucket: 'catalog',
    from: 'Dated conversion rates, a single static rate',
    to: 'A manually set HubSpot exchange rate',
    verdict: 'Clear path',
    shape: '1:1',
  },
  {
    id: 'catalog.dcrTable',
    bucket: 'catalog',
    from: 'Dated conversion rates, a maintained rate table',
    to: 'HubSpot holds one current rate per currency — a rate cannot be authored against a period',
    verdict: 'Degraded',
  },
  {
    id: 'configuration.bundles',
    bucket: 'configuration',
    from: 'Bundles, features, options, quantity bounds',
    to: 'Bundles, bundle options, option products',
    verdict: 'Clear path',
    shape: '1:1',
  },
  {
    id: 'configuration.exclusion',
    bucket: 'configuration',
    from: 'Option constraints — exclusion',
    to: 'Compatibility Rules',
    verdict: 'Clear path',
    shape: '1:1',
  },
  {
    id: 'configuration.dependency',
    bucket: 'configuration',
    from: 'Option constraints — dependency ("requires")',
    to: 'Already satisfied when the required option is included with a default; otherwise Add add-on or Block',
    verdict: 'Degraded',
  },
  {
    id: 'configuration.minMax',
    bucket: 'configuration',
    from: 'Feature min/max option counts',
    to: '"Pick one" and "Pick one or more" are native; a numeric cap needs a roll-up + Block',
    verdict: 'Degraded',
  },
  {
    id: 'configuration.nested',
    bucket: 'configuration',
    from: 'Nested bundles',
    to: '—',
    verdict: 'No target',
  },
  {
    id: 'configuration.filter',
    bucket: 'configuration',
    from: 'Dynamic option sets (filter rules)',
    to: '—',
    verdict: 'No target',
  },
  {
    id: 'configuration.lookup',
    bucket: 'configuration',
    from: 'Lookup queries on a product rule',
    to: 'Depends on the custom object behind them, which the tool cannot read',
    verdict: 'Further review',
  },
  {
    id: 'discovery.attributes',
    bucket: 'discovery',
    from: 'Configuration attributes',
    to: 'Header property + Update Bundle Members, or Guided Selling',
    verdict: 'Clear path',
    shape: '1:1',
  },
  {
    id: 'discovery.guided',
    bucket: 'discovery',
    from: 'Guided selling processes',
    to: 'Guided Selling flows + questions',
    verdict: 'Clear path',
    shape: '1:1',
  },
  {
    id: 'price.tiers',
    bucket: 'price',
    from: 'Volume and tier pricing, attribute pricing',
    to: 'Price book adjustments, pricing tables, variants',
    verdict: 'Clear path',
    shape: '1:1',
  },
  {
    id: 'price.calculated',
    bucket: 'price',
    from: 'Cost-plus, percent-of-total, block pricing',
    to: 'Calculated pricing (+ roll-ups)',
    verdict: 'Clear path',
    shape: 'Fan-out',
  },
  {
    id: 'price.mdq',
    bucket: 'price',
    from: 'MDQ / segmented subscription pricing',
    to: 'Ramp pricing; Update Bundle Members rules when bundled. Stepped quantity does not carry',
    verdict: 'Degraded',
  },
  {
    id: 'price.term',
    bucket: 'price',
    from: 'Subscription term and proration maths',
    to: '—',
    verdict: 'No target',
  },
  {
    id: 'price.lookup',
    bucket: 'price',
    from: 'Lookup queries on a price rule',
    to: 'Depends on the custom object behind them, which the tool cannot read',
    verdict: 'Further review',
  },
  {
    id: 'discounting.tiers',
    bucket: 'discounting',
    from: 'Discount schedules, per-line tiers',
    to: 'Volume pricing tiers',
    verdict: 'Clear path',
    shape: '1:1',
  },
  {
    id: 'discounting.quote',
    bucket: 'discounting',
    from: 'Schedules aggregating across the quote',
    to: 'Quote-wide roll-up + calculated pricing formula',
    verdict: 'Clear path',
    shape: 'Fan-out',
  },
  {
    id: 'discounting.group',
    bucket: 'discounting',
    from: 'Schedules aggregating across a quote line group',
    to: 'Roll-up quote-wide or per bundle — grouping itself carries no functional aggregate',
    verdict: 'Degraded',
  },
  {
    id: 'discounting.contracted',
    bucket: 'discounting',
    from: 'Contracted pricing',
    to: 'Price books assigned to companies',
    verdict: 'Clear path',
    shape: 'Fan-out',
  },
  {
    id: 'guardrails.validation',
    bucket: 'guardrails',
    from: 'Validation rules',
    to: 'Block',
    verdict: 'Clear path',
    shape: '1:1',
  },
  {
    id: 'guardrails.alert',
    bucket: 'guardrails',
    from: 'Alert rules',
    to: 'Notify',
    verdict: 'Clear path',
    shape: '1:1',
  },
  {
    id: 'guardrails.flags',
    bucket: 'guardrails',
    from: 'Non-discountable, price-not-editable',
    to: 'Price book editability, property-set rules',
    verdict: 'Clear path',
    shape: '1:1',
  },
  {
    id: 'guardrails.custom',
    bucket: 'guardrails',
    from: 'Custom boolean condition logic on a rule',
    to: 'Condition groups, the expression flattened',
    verdict: 'Clear path',
    shape: 'Fan-out',
  },
  {
    id: 'approvals.rules',
    bucket: 'approvals',
    from: 'Approval rules and conditions',
    to: 'Require Approval + approval queue',
    verdict: 'Clear path',
    shape: '1:1',
  },
  {
    id: 'approvals.chains',
    bucket: 'approvals',
    from: 'Approval chains, ordering',
    to: 'Stacked Request Quote Approval (v2) actions in a HubSpot workflow',
    verdict: 'Clear path',
    shape: 'Rebuild',
  },
  {
    id: 'approvals.derived',
    bucket: 'approvals',
    from: 'Derived approvers, escalation',
    to: 'Workflow routing',
    verdict: 'Degraded',
  },
  {
    id: 'output.groups',
    bucket: 'output',
    from: 'Quote line groups',
    to: 'Template grouping of line items by a line item property',
    verdict: 'Clear path',
    shape: '1:1',
  },
  {
    id: 'output.templates',
    bucket: 'output',
    from: 'Quote templates, sections, columns, terms',
    to: 'Quotivity Templates, Terms Library',
    verdict: 'Clear path',
    shape: 'Rebuild',
  },
  {
    id: 'lifecycle.renewals',
    bucket: 'lifecycle',
    from: 'Amendments, prorations, renewals',
    to: 'HubSpot Contracts, change and renewal quotes',
    verdict: 'Clear path',
    shape: '1:1',
  },
  {
    id: 'lifecycle.orders',
    bucket: 'lifecycle',
    from: 'Orders, assets',
    to: '—',
    verdict: 'No target',
  },
  {
    id: 'code.custom',
    bucket: 'code',
    from: 'QCP, triggers and UI customisations on CPQ objects',
    to: 'Calculated pricing, most likely — listed, not interpreted',
    verdict: 'Further review',
  },
];

export const VERDICT_MEANINGS: Record<Exclude<Verdict, 'Further review'>, string> = {
  'Clear path': 'The behaviour survives and the route to it is known',
  Degraded: 'The behaviour survives in part. The report names what is lost',
  'No target': 'The behaviour does not survive. Needs a redesign or a product change',
};

export const SHAPE_MEANINGS: Record<Shape, string> = {
  '1:1': 'One record becomes one record',
  'Fan-out': 'One construct becomes several records, or several collapse into one',
  Rebuild: 'Authored fresh in the target rather than imported',
};
